### ISSUE TITLE
Error getting podcast

### ISSUE THREAD

**Issue by solskogen** [jakobbg/poddie#1]
solskogen@friend:~/poddie$ php poddie.php
PHP Notice:  Undefined offset: 2 in /data/home/solskogen/poddie/poddie.php on line 13
Removing #0 from Alt du sier er feil, Espen - med Kristopher Schau & Espen Thoresen (/home/solskogen/storage/Audio/Podcasts/Alt du sier er feil, Espen - med Kristopher Schau & Espen Thoresen/)
PHP Warning:  unlink(/home/solskogen/storage/Audio/Podcasts/Alt du sier er feil, Espen - med Kristopher Schau & Espen Thoresen/): Is a directory in /data/home/solskogen/poddie/poddie.php on line 50
PHP Notice:  Undefined offset: 1 in /data/home/solskogen/poddie/poddie.php on line 13
PHP Notice:  Undefined offset: 2 in /data/home/solskogen/poddie/poddie.php on line 13
 () does not exist. Skipping.
solskogen@friend:~/poddie$ cat poddie.feeds
Misjonen;http://www.p4.no/lyttesenter/podcast.ashx?pid=330;5000
Alt du sier er feil, Espen - med Kristopher Schau & Espen Thoresen;http://rss.acast.com/altdusiererfeil

solskogen@friend:~/poddie$ cat poddie.config
timezone = "UTC";
id3tag = "/usr/bin/id3tag";
podcast_storage = "/home/solskogen/storage/Audio/Podcasts";

**Comment by jakobbg** [comment]
Will investigate, but can this be related to title including the & sign? Might need to involve some more robustness.

**Comment by jakobbg** [comment]
I have the same podcast, with the following config;

`Alt du sier er feil, Espen;http://rss.acast.com/altdusiererfeil;5`

**Comment by jakobbg** [comment]
Closing, error in user config.
